nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.5.3.cjs

packageExtensions:
  '@chakra-ui/react@*':
    peerDependencies:
      react: '18.x'
      'react-dom': '18.x'
  'next@*':
    peerDependencies:
      react: '18.x'
      'react-dom': '18.x'
